# Generated by Django 5.2.7 on 2025-10-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_private',
            field=models.CharField(blank=True, choices=[(True, 'Private'), (False, 'Public')], max_length=20, null=True),
        ),
    ]
