# Generated by Django 5.2.7 on 2025-10-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_snippet_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='is_private',
            field=models.BooleanField(blank=True, choices=[(True, 'Private'), (False, 'Public')], null=True),
        ),
    ]
